---

- name: VM from template
  hosts: vmcreate
  gather_facts: false
  connection: local
  vars:
    vcenter_hostname: 192.168.222.19
    esxhost: 192.168.222.17
    vcenter_user: yxiong
    vcenter_pass: Oursonkuma121-
    datastore: Nexenta-112-VM
    network: "VMnetwork"
    vmtemplate: Debian8-x64-Template
    vmcluster: CLICHY
    notes: Created by Ansible
    name: testvm2
    dumpfacts: False
  tasks:
    - name: Create VM from template
      vmware_guest:
        validate_certs: False
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        esxi_hostname: "{{ esxhost }}"
        datacenter: OPENIP-LAB
        name: "{{ name }}"
        template: "{{ vmtemplate }}"
        disk:
          - size_gb: "{{ disk_size | default(20) }}"
            type: thin
            datastore: "{{ datastore }}"
        nic:
          - type: vmxnet3
            network: "{{ network }}"
        hardware:
          memory_mb: "{{ vm_memory | default(1024) }}"
        wait_for_ip_address: True
        state: present
      register: newvm
